server:
  port: 8080

spring:
  datasource:
    username: root
    password: 302232
    url: jdbc:mysql://localhost:3306/crud_user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xzb.demo.entity


